export const DataKaryawan = [
  {
    id: 1,
    nama: "Armstrong Fernando",
    tanggalLahir: "2004/10/08",
    alamat: "5489 Glacier Hill Way",
    email: "afernando0@jugem.jp",
  },
  {
    id: 2,
    nama: "Lauralee Lammerich",
    tanggalLahir: "2011/03/05",
    alamat: "29 Barby Plaza",
    email: "llammerich1@phpbb.com",
  },
  {
    id: 3,
    nama: "Clarice Jerred",
    tanggalLahir: "2001/11/25",
    alamat: "43962 Kinsman Street",
    email: "cjerred2@list-manage.com",
  },
  {
    id: 4,
    nama: "Christy Tunstall",
    tanggalLahir: "2014/05/12",
    alamat: "06254 Cambridge Alley",
    email: "ctunstall3@youtube.com",
  },
  {
    id: 5,
    nama: "Brigida Ahlf",
    tanggalLahir: "2011/05/12",
    alamat: "41 Lillian Court",
    email: "bahlf4@t-online.de",
  },
  {
    id: 6,
    nama: "Sheree Henzley",
    tanggalLahir: "2001/12/23",
    alamat: "41655 Artisan Parkway",
    email: "shenzley5@state.tx.us",
  },
  {
    id: 7,
    nama: "Giffer Attwood",
    tanggalLahir: "2009/02/26",
    alamat: "632 Waubesa Point",
    email: "gattwood6@wiley.com",
  },
  {
    id: 8,
    nama: "Crystal Willman",
    tanggalLahir: "2014/03/16",
    alamat: "1 Vahlen Plaza",
    email: "cwillman7@ca.gov",
  },
  {
    id: 9,
    nama: "Marya Schrader",
    tanggalLahir: "2005/08/21",
    alamat: "435 Prairieview Park",
    email: "mschrader8@instagram.com",
  },
  {
    id: 10,
    nama: "Anthe Crandon",
    tanggalLahir: "2008/04/24",
    alamat: "209 Harbort Parkway",
    email: "acrandon9@php.net",
  },
  {
    id: 11,
    nama: "Gene Queripel",
    tanggalLahir: "2002/01/25",
    alamat: "339 Morningstar Point",
    email: "gqueripela@wsj.com",
  },
  {
    id: 12,
    nama: "Julie Djokic",
    tanggalLahir: "2011/05/27",
    alamat: "606 Eastlawn Point",
    email: "jdjokicb@flickr.com",
  },
  {
    id: 13,
    nama: "Brittany Delhanty",
    tanggalLahir: "2011/03/31",
    alamat: "24 Autumn Leaf Place",
    email: "bdelhantyc@slashdot.org",
  },
  {
    id: 14,
    nama: "Elroy Tesoe",
    tanggalLahir: "2005/12/07",
    alamat: "30 Moose Terrace",
    email: "etesoed@prlog.org",
  },
  {
    id: 15,
    nama: "Leelah Alywen",
    tanggalLahir: "2007/03/03",
    alamat: "2301 Columbus Street",
    email: "lalywene@columbia.edu",
  },
  {
    id: 16,
    nama: "Maurita Roofe",
    tanggalLahir: "2006/05/14",
    alamat: "228 Coolidge Way",
    email: "mroofef@privacy.gov.au",
  },
  {
    id: 17,
    nama: "Sawyere Lody",
    tanggalLahir: "2012/08/18",
    alamat: "2 John Wall Center",
    email: "slodyg@ca.gov",
  },
  {
    id: 18,
    nama: "Leticia Southgate",
    tanggalLahir: "2008/08/16",
    alamat: "63118 Carpenter Junction",
    email: "lsouthgateh@mapquest.com",
  },
  {
    id: 19,
    nama: "Kelcey Bollans",
    tanggalLahir: "2012/02/20",
    alamat: "449 Gina Junction",
    email: "kbollansi@bizjournals.com",
  },
  {
    id: 20,
    nama: "Maure Youngman",
    tanggalLahir: "2002/11/27",
    alamat: "12 Village Way",
    email: "myoungmanj@pen.io",
  },
  {
    id: 21,
    nama: "Dulcea Belderson",
    tanggalLahir: "2011/01/31",
    alamat: "614 Muir Trail",
    email: "dbeldersonk@yellowbook.com",
  },
  {
    id: 22,
    nama: "Barret Kavanagh",
    tanggalLahir: "2007/04/30",
    alamat: "4 Comanche Avenue",
    email: "bkavanaghl@google.it",
  },
  {
    id: 23,
    nama: "Sisile Wipper",
    tanggalLahir: "2008/08/05",
    alamat: "509 Pierstorff Street",
    email: "swipperm@mtv.com",
  },
  {
    id: 24,
    nama: "Gal Broadbere",
    tanggalLahir: "2006/03/14",
    alamat: "972 Thompson Terrace",
    email: "gbroadberen@themeforest.net",
  },
  {
    id: 25,
    nama: "Opal Struis",
    tanggalLahir: "2007/11/18",
    alamat: "1 Rockefeller Drive",
    email: "ostruiso@twitter.com",
  },
  {
    id: 26,
    nama: "Janean Blakes",
    tanggalLahir: "2012/04/28",
    alamat: "3 Rieder Way",
    email: "jblakesp@cisco.com",
  },
  {
    id: 27,
    nama: "Caspar Minall",
    tanggalLahir: "2006/07/02",
    alamat: "90680 Boyd Hill",
    email: "cminallq@toplist.cz",
  },
  {
    id: 28,
    nama: "Kitty Baldam",
    tanggalLahir: "2014/02/03",
    alamat: "42 Buhler Crossing",
    email: "kbaldamr@theguardian.com",
  },
  {
    id: 29,
    nama: "Nichole Waldera",
    tanggalLahir: "2002/07/07",
    alamat: "54913 Autumn Leaf Pass",
    email: "nwalderas@walmart.com",
  },
  {
    id: 30,
    nama: "Jehu Miquelet",
    tanggalLahir: "2012/01/07",
    alamat: "99 Dryden Avenue",
    email: "jmiquelett@webmd.com",
  },
  {
    id: 31,
    nama: "Deanne Rash",
    tanggalLahir: "2011/01/10",
    alamat: "35801 Transport Circle",
    email: "drashu@eepurl.com",
  },
  {
    id: 32,
    nama: "Wallie Ofener",
    tanggalLahir: "2006/05/21",
    alamat: "576 Sheridan Way",
    email: "wofenerv@imgur.com",
  },
  {
    id: 33,
    nama: "Carling Cardew",
    tanggalLahir: "2006/02/27",
    alamat: "7861 Onsgard Circle",
    email: "ccardeww@yandex.ru",
  },
  {
    id: 34,
    nama: "Nappie Rafter",
    tanggalLahir: "2005/05/04",
    alamat: "45 Darwin Place",
    email: "nrafterx@mail.ru",
  },
  {
    id: 35,
    nama: "Rudolfo Bottjer",
    tanggalLahir: "2003/10/28",
    alamat: "552 Glendale Center",
    email: "rbottjery@merriam-webster.com",
  },
  {
    id: 36,
    nama: "Gerik Callinan",
    tanggalLahir: "2009/06/18",
    alamat: "393 Sugar Plaza",
    email: "gcallinanz@t.co",
  },
  {
    id: 37,
    nama: "Athena Muro",
    tanggalLahir: "2003/12/19",
    alamat: "753 Bunker Hill Center",
    email: "amuro10@go.com",
  },
  {
    id: 38,
    nama: "Claudina Stansbury",
    tanggalLahir: "2009/01/29",
    alamat: "698 Havey Point",
    email: "cstansbury11@geocities.com",
  },
  {
    id: 39,
    nama: "Nancie Risby",
    tanggalLahir: "2007/11/29",
    alamat: "44 Karstens Pass",
    email: "nrisby12@theatlantic.com",
  },
  {
    id: 40,
    nama: "Haily Driffe",
    tanggalLahir: "2005/11/27",
    alamat: "26319 Shopko Center",
    email: "hdriffe13@devhub.com",
  },
  {
    id: 41,
    nama: "Billie Roostan",
    tanggalLahir: "2008/08/28",
    alamat: "31133 Declaration Center",
    email: "broostan14@wired.com",
  },
  {
    id: 42,
    nama: "Rorie Cavee",
    tanggalLahir: "2011/06/26",
    alamat: "74 Mandrake Crossing",
    email: "rcavee15@about.com",
  },
  {
    id: 43,
    nama: "Florida Astill",
    tanggalLahir: "2007/10/26",
    alamat: "266 Pond Avenue",
    email: "fastill16@statcounter.com",
  },
  {
    id: 44,
    nama: "Stephenie Drinkale",
    tanggalLahir: "2006/04/22",
    alamat: "526 Westend Terrace",
    email: "sdrinkale17@surveymonkey.com",
  },
  {
    id: 45,
    nama: "Thia McGarrie",
    tanggalLahir: "2011/08/01",
    alamat: "88866 Loeprich Terrace",
    email: "tmcgarrie18@fda.gov",
  },
  {
    id: 46,
    nama: "Cariotta Westman",
    tanggalLahir: "2013/05/14",
    alamat: "22 Fordem Circle",
    email: "cwestman19@berkeley.edu",
  },
  {
    id: 47,
    nama: "Bernadette Brouwer",
    tanggalLahir: "2013/05/19",
    alamat: "924 Burning Wood Road",
    email: "bbrouwer1a@dyndns.org",
  },
  {
    id: 48,
    nama: "Yurik Bassick",
    tanggalLahir: "2008/07/06",
    alamat: "64 2nd Junction",
    email: "ybassick1b@omniture.com",
  },
  {
    id: 49,
    nama: "Belia Williamson",
    tanggalLahir: "2002/10/09",
    alamat: "892 Garrison Junction",
    email: "bwilliamson1c@purevolume.com",
  },
  {
    id: 50,
    nama: "Rafa Corrado",
    tanggalLahir: "2004/01/24",
    alamat: "410 Waubesa Park",
    email: "rcorrado1d@dailymail.co.uk",
  },
  {
    id: 51,
    nama: "Jaye Billingsly",
    tanggalLahir: "2011/03/05",
    alamat: "400 Manley Street",
    email: "jbillingsly1e@youtu.be",
  },
  {
    id: 52,
    nama: "Gal Garlette",
    tanggalLahir: "2014/01/04",
    alamat: "2280 Waxwing Plaza",
    email: "ggarlette1f@gmpg.org",
  },
  {
    id: 53,
    nama: "Claudina Marchington",
    tanggalLahir: "2003/03/15",
    alamat: "2271 North Plaza",
    email: "cmarchington1g@slate.com",
  },
  {
    id: 54,
    nama: "Huberto Denyer",
    tanggalLahir: "2007/12/21",
    alamat: "76506 Farmco Hill",
    email: "hdenyer1h@intel.com",
  },
  {
    id: 55,
    nama: "Arv Pietrowicz",
    tanggalLahir: "2014/06/11",
    alamat: "6 Forest Dale Court",
    email: "apietrowicz1i@msu.edu",
  },
  {
    id: 56,
    nama: "Reynolds Antuoni",
    tanggalLahir: "2009/03/20",
    alamat: "7118 Sugar Hill",
    email: "rantuoni1j@adobe.com",
  },
  {
    id: 57,
    nama: "Bran Millar",
    tanggalLahir: "2007/12/10",
    alamat: "49 8th Parkway",
    email: "bmillar1k@bloglovin.com",
  },
  {
    id: 58,
    nama: "Adam Craythorne",
    tanggalLahir: "2013/03/04",
    alamat: "0 Buena Vista Circle",
    email: "acraythorne1l@indiatimes.com",
  },
  {
    id: 59,
    nama: "Foss Bagg",
    tanggalLahir: "2011/05/12",
    alamat: "30191 Bultman Point",
    email: "fbagg1m@seesaa.net",
  },
  {
    id: 60,
    nama: "Courtney Yusupov",
    tanggalLahir: "2001/09/26",
    alamat: "12 Claremont Place",
    email: "cyusupov1n@ameblo.jp",
  },
  {
    id: 61,
    nama: "Asia Pope",
    tanggalLahir: "2011/04/17",
    alamat: "4647 Blackbird Crossing",
    email: "apope1o@ning.com",
  },
  {
    id: 62,
    nama: "Ivette Buckberry",
    tanggalLahir: "2010/07/05",
    alamat: "8 Oriole Drive",
    email: "ibuckberry1p@umn.edu",
  },
  {
    id: 63,
    nama: "Michail Middell",
    tanggalLahir: "2006/05/03",
    alamat: "94 Blackbird Pass",
    email: "mmiddell1q@cyberchimps.com",
  },
  {
    id: 64,
    nama: "Roley Creech",
    tanggalLahir: "2011/09/29",
    alamat: "4 Cardinal Avenue",
    email: "rcreech1r@github.io",
  },
  {
    id: 65,
    nama: "Uriel Arnholz",
    tanggalLahir: "2006/04/12",
    alamat: "95046 Eagle Crest Road",
    email: "uarnholz1s@sphinn.com",
  },
  {
    id: 66,
    nama: "Lyssa Delagua",
    tanggalLahir: "2013/05/24",
    alamat: "4 Rockefeller Pass",
    email: "ldelagua1t@mashable.com",
  },
  {
    id: 67,
    nama: "Durant Janko",
    tanggalLahir: "2002/05/06",
    alamat: "60 Melody Park",
    email: "djanko1u@amazon.com",
  },
  {
    id: 68,
    nama: "Verine Quesne",
    tanggalLahir: "2006/11/09",
    alamat: "237 Mifflin Drive",
    email: "vquesne1v@sbwire.com",
  },
  {
    id: 69,
    nama: "Odey Bentje",
    tanggalLahir: "2008/08/23",
    alamat: "9 Farwell Drive",
    email: "obentje1w@china.com.cn",
  },
  {
    id: 70,
    nama: "Bax Walder",
    tanggalLahir: "2006/01/05",
    alamat: "528 Bunker Hill Trail",
    email: "bwalder1x@home.pl",
  },
  {
    id: 71,
    nama: "Aldin Simonich",
    tanggalLahir: "2006/10/04",
    alamat: "03 Continental Drive",
    email: "asimonich1y@unc.edu",
  },
  {
    id: 72,
    nama: "Alden Heeps",
    tanggalLahir: "2012/09/27",
    alamat: "319 Northview Alley",
    email: "aheeps1z@hhs.gov",
  },
  {
    id: 73,
    nama: "Alicea Horney",
    tanggalLahir: "2007/06/03",
    alamat: "8897 American Ash Park",
    email: "ahorney20@nyu.edu",
  },
  {
    id: 74,
    nama: "Tobi Damper",
    tanggalLahir: "2004/11/27",
    alamat: "6137 Buell Pass",
    email: "tdamper21@marketwatch.com",
  },
  {
    id: 75,
    nama: "Cybill Fawdrey",
    tanggalLahir: "2014/05/29",
    alamat: "309 Spohn Plaza",
    email: "cfawdrey22@hc360.com",
  },
  {
    id: 76,
    nama: "Tuck Wilkinson",
    tanggalLahir: "2003/10/30",
    alamat: "1489 Hagan Hill",
    email: "twilkinson23@artisteer.com",
  },
  {
    id: 77,
    nama: "Ritchie Hellard",
    tanggalLahir: "2011/10/05",
    alamat: "109 Eliot Court",
    email: "rhellard24@unesco.org",
  },
  {
    id: 78,
    nama: "Hollie Kirkup",
    tanggalLahir: "2014/04/08",
    alamat: "2238 Everett Road",
    email: "hkirkup25@blogspot.com",
  },
  {
    id: 79,
    nama: "Brockie Benardeau",
    tanggalLahir: "2002/11/09",
    alamat: "5173 Monterey Avenue",
    email: "bbenardeau26@plala.or.jp",
  },
  {
    id: 80,
    nama: "Zarla Bobasch",
    tanggalLahir: "2003/08/14",
    alamat: "12390 School Pass",
    email: "zbobasch27@businessweek.com",
  },
];

export const DataJabatan = [
  {
    id: 1,
    jabatan: "Staff Scientist",
    gajiPokok: "$210.94",
    thr: "$133.89",
    tunjangan: "$334.30",
  },
  {
    id: 2,
    jabatan: "Graphic Designer",
    gajiPokok: "$109.66",
    thr: "$91.42",
    tunjangan: "$30.85",
  },
  {
    id: 3,
    jabatan: "Financial Analyst",
    gajiPokok: "$149.70",
    thr: "$123.13",
    tunjangan: "$107.42",
  },
  {
    id: 4,
    jabatan: "Cost Accountant",
    gajiPokok: "$495.74",
    thr: "$77.70",
    tunjangan: "$412.74",
  },
  {
    id: 5,
    jabatan: "Engineer IV",
    gajiPokok: "$383.24",
    thr: "$97.20",
    tunjangan: "$268.77",
  },
  {
    id: 6,
    jabatan: "Civil Engineer",
    gajiPokok: "$349.49",
    thr: "$14.42",
    tunjangan: "$357.82",
  },
  {
    id: 7,
    jabatan: "Structural Engineer",
    gajiPokok: "$54.98",
    thr: "$105.09",
    tunjangan: "$353.29",
  },
  {
    id: 8,
    jabatan: "Administrative Officer",
    gajiPokok: "$475.00",
    thr: "$31.57",
    tunjangan: "$9.31",
  },
  {
    id: 9,
    jabatan: "Marketing Assistant",
    gajiPokok: "$87.25",
    thr: "$10.83",
    tunjangan: "$409.37",
  },
  {
    id: 10,
    jabatan: "Mechanical Systems Engineer",
    gajiPokok: "$83.18",
    thr: "$69.82",
    tunjangan: "$133.79",
  },
  {
    id: 11,
    jabatan: "Junior Executive",
    gajiPokok: "$200.75",
    thr: "$65.30",
    tunjangan: "$152.35",
  },
  {
    id: 12,
    jabatan: "GIS Technical Architect",
    gajiPokok: "$66.93",
    thr: "$58.82",
    tunjangan: "$289.14",
  },
  {
    id: 13,
    jabatan: "Marketing Assistant",
    gajiPokok: "$166.97",
    thr: "$43.20",
    tunjangan: "$285.96",
  },
  {
    id: 14,
    jabatan: "Technical Writer",
    gajiPokok: "$103.94",
    thr: "$83.30",
    tunjangan: "$80.99",
  },
];
